### ISSUE TITLE
sources.list: need panda instead of kui

### ISSUE THREAD

**Issue by mviereck** [panhaitao/deepin-core#3]
Hello!

Your `sources.list` points to branch `kui`. But the repository provides `panda` now.
Please correct that.

Thanks!

**Comment by panhaitao** [comment]
codename kui is for deepin server , the repository is http://mirrors.deepin.com/deepin-server/ 
but codename panda is for deepin desktop, the repository is http://mirrors.deepin.com/deepin/

**Comment by mviereck** [comment]
Thank you for clarification!
